In [115]:
import numpy as np

In [116]:
list1=[1,3,6,8]
ar2=np.array(list1)
ar2
# Here is the 1D array 

array([1, 3, 6, 8])

In [117]:
list2=[1,3,6,8],[5,4,33,83]
ar2=np.array(list2)
ar2
# it is an 2*4 matrix 2d array 

array([[ 1,  3,  6,  8],
       [ 5,  4, 33, 83]])

In [118]:
np.arange(1,20)
# it give a range between two numbers 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [119]:
# I can also give a step size 
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [120]:
np.zeros(5)
# It is the array of zeros 

array([0., 0., 0., 0., 0.])

In [121]:
np.ones(4)

array([1., 1., 1., 1.])

In [122]:
np.ones((3,4))  #2d array 


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [123]:
np.linspace(1,12,100)
# it generate 100 value between 1 to 12 with equaly spaced..

array([ 1.        ,  1.11111111,  1.22222222,  1.33333333,  1.44444444,
        1.55555556,  1.66666667,  1.77777778,  1.88888889,  2.        ,
        2.11111111,  2.22222222,  2.33333333,  2.44444444,  2.55555556,
        2.66666667,  2.77777778,  2.88888889,  3.        ,  3.11111111,
        3.22222222,  3.33333333,  3.44444444,  3.55555556,  3.66666667,
        3.77777778,  3.88888889,  4.        ,  4.11111111,  4.22222222,
        4.33333333,  4.44444444,  4.55555556,  4.66666667,  4.77777778,
        4.88888889,  5.        ,  5.11111111,  5.22222222,  5.33333333,
        5.44444444,  5.55555556,  5.66666667,  5.77777778,  5.88888889,
        6.        ,  6.11111111,  6.22222222,  6.33333333,  6.44444444,
        6.55555556,  6.66666667,  6.77777778,  6.88888889,  7.        ,
        7.11111111,  7.22222222,  7.33333333,  7.44444444,  7.55555556,
        7.66666667,  7.77777778,  7.88888889,  8.        ,  8.11111111,
        8.22222222,  8.33333333,  8.44444444,  8.55555556,  8.66

In [124]:
a2= np.linspace(1,12,100)

In [125]:
a2.shape
# a2 is 1D and 100 values 

(100,)

In [126]:
ar2

array([[ 1,  3,  6,  8],
       [ 5,  4, 33, 83]])

In [127]:
ar2.shape
# ar2 is 2*4 matrix 2D array

(2, 4)

In [128]:
a2.dtype
# a2 has a float values 

dtype('float64')

In [129]:
ar2.dtype
# it has integer values

dtype('int32')

In [130]:
np.eye(4)
# i can generate identity matrix 4*4 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [131]:
a2

array([ 1.        ,  1.11111111,  1.22222222,  1.33333333,  1.44444444,
        1.55555556,  1.66666667,  1.77777778,  1.88888889,  2.        ,
        2.11111111,  2.22222222,  2.33333333,  2.44444444,  2.55555556,
        2.66666667,  2.77777778,  2.88888889,  3.        ,  3.11111111,
        3.22222222,  3.33333333,  3.44444444,  3.55555556,  3.66666667,
        3.77777778,  3.88888889,  4.        ,  4.11111111,  4.22222222,
        4.33333333,  4.44444444,  4.55555556,  4.66666667,  4.77777778,
        4.88888889,  5.        ,  5.11111111,  5.22222222,  5.33333333,
        5.44444444,  5.55555556,  5.66666667,  5.77777778,  5.88888889,
        6.        ,  6.11111111,  6.22222222,  6.33333333,  6.44444444,
        6.55555556,  6.66666667,  6.77777778,  6.88888889,  7.        ,
        7.11111111,  7.22222222,  7.33333333,  7.44444444,  7.55555556,
        7.66666667,  7.77777778,  7.88888889,  8.        ,  8.11111111,
        8.22222222,  8.33333333,  8.44444444,  8.55555556,  8.66

In [132]:
a2.max()
# it gives the maximum value in the aaray 

12.0

In [133]:
a2.min()
# it gives the minimum value in the aaray 

1.0

In [134]:
a2.argmax()
# also find argument or position  

99

In [135]:
a2.argmin()

0

In [136]:
np.random.rand(3)
# it gives 3 values randomly between 0 and 1 

array([0.62344513, 0.22383316, 0.99163556])

In [137]:
np.random.rand(3,3)
# 2D array with random values 

array([[0.91592225, 0.3230495 , 0.47232945],
       [0.88443928, 0.98562751, 0.06635019],
       [0.56299149, 0.69707092, 0.01560439]])

In [138]:
np.random.randn(3,3)
# normal distribution betweeen -1 and +1 

array([[-1.29705034, -0.89505233,  0.84208885],
       [ 0.51824085,  2.02413836, -1.08016532],
       [ 0.68391398, -0.4844945 , -0.46918985]])

In [139]:
np.random.randint(1,100,10)
# it in randomly generated values between 10 and 100 and we have 10 values 

array([31, 55, 23, 74, 42, 23, 24,  6, 76, 49])

In [140]:
a1=np.arange(5,101,5)

In [141]:
a1

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [142]:
a2=a1.reshape(5,4)

In [143]:
a2.shape

(5, 4)

In [144]:
a2

array([[  5,  10,  15,  20],
       [ 25,  30,  35,  40],
       [ 45,  50,  55,  60],
       [ 65,  70,  75,  80],
       [ 85,  90,  95, 100]])

In [145]:
a2[1:3,2:4]
# it look at rows 1 to 3
# and columns 2 to 4 

array([[35, 40],
       [55, 60]])

In [146]:
a2[3,:]
# complete 3 row 

array([65, 70, 75, 80])

In [147]:
a2[:,3]
# print complete column 

array([ 20,  40,  60,  80, 100])

In [148]:
aslice=a2[3,:]

In [149]:
aslice[:]=100

In [150]:
aslice

array([100, 100, 100, 100])

In [151]:
a2
# alice replace the value form a2 also 

array([[  5,  10,  15,  20],
       [ 25,  30,  35,  40],
       [ 45,  50,  55,  60],
       [100, 100, 100, 100],
       [ 85,  90,  95, 100]])

In [152]:
acopy=a2.copy()

In [153]:
acopy[:]=100

In [154]:
acopy

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [155]:
a2

array([[  5,  10,  15,  20],
       [ 25,  30,  35,  40],
       [ 45,  50,  55,  60],
       [100, 100, 100, 100],
       [ 85,  90,  95, 100]])

In [156]:
a2>50
# boolean value assign 

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [157]:
a1=np.arange(0,11)
a2=np.arange(0,21,2)

In [158]:
a1.shape

(11,)

In [159]:
a2.shape

(11,)

In [160]:
a1+a2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [161]:
a1+a2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [162]:
a2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [163]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [164]:
a1-a2

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10])

In [165]:
a2-a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [166]:
a1*a2

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162, 200])

In [167]:
a1/a2

C:\Users\my-pc\anaconda3\envs\credit\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [168]:
np.sqrt(a1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [169]:
np.sqrt(a2)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595])

In [170]:
np.exp(a1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [171]:
np.sin(a1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [172]:
np.log(a1)

C:\Users\my-pc\anaconda3\envs\credit\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])